name: CI

on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]

jobs:
  export-deployments:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        # Hack to get around failing "ethereumjs-abi The remote archive doesn't match the expected checksum" error
        run: YARN_CHECKSUM_BEHAVIOR=update yarn

      - name: Export deployments
        run: |
          for NETWORK in ethereum sepolia arbitrum base metertest metermain; do
            EXPORT=true yarn hardhat export --network ${NETWORK} --export ./deployments/${NETWORK}.json
            jq -M '{name, chainId, addresses: .contracts | map_values(.address)}' ./deployments/${NETWORK}.json > ./deployments/${NETWORK}_addresses.json
          done
          yarn prettier

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: updating deployment files"
          file_pattern: "deployments/*.json"
